version: "3.9"

services:
  fieldphotos:
    image: kartoza/geoserver:2.21.1
    ports:
      - "9992:8080"
    environment:
      GEOSERVER_DATA_DIR: /geoserver
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: icem
    volumes:
      - ./tomcat/ROOT:/usr/local/tomcat/webapps/ROOT
      - ./tomcat/geoserver/WEB-INF:/usr/local/tomcat/webapps/geoserver/WEB-INF
      - ./tomcat/geoserver/data:/geoserver
    restart: always