version: "3.9"

services:
  gs:
    build:
      dockerfile: ./Dockerfile
    container_name: geofp
    image: ptm/geoserver:my_test
    ports:
      - "9992:8080"
    environment:
      GEOSERVER_DATA_DIR: /geoserver
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: icem
      STABLE_EXTENSIONS: charts-plugin, css-plugin, dxf-plugin, excel-plugin, geopkg-output-plugin, h2-plugin, imagemap-plugin, importer-plugin, jp2k-plugin, mapml-plugin, mbstyle-plugin, mysql-plugin, netcdf-plugin, querylayer-plugin, xslt-plugin, ysld-plugin
    volumes:
      - ./tomcat/ROOT:/usr/local/tomcat/webapps/ROOT
    #  - ./tomcat/geoserver/WEB-INF/lib:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib
      - ./tomcat/geoserver/data:/geoserver
    #  - ./tomcat/fonts:/opt/fonts
    restart: always
  pg:
    build: 
      dockerfile: ./Dockerfile_PostGIS
  pgadmin:
    build: 
    environment:
      - name=value
  shiny:
    build:
      dockerfile: ./Dockerfile_shiny
      container_name: Fieldphotos
      image: ptm/shiny:4.1.3
      ports:
        - "9990:3838"
      environtment:
      volume:
        - 
      restart: always